### ISSUE TITLE
朋友，能把每部电影的海报URL放在q.json中吗？

### ISSUE THREAD

**Issue by aizhimou** [Rocket-Factory/DoubanMovieJSON#1]
这样在 https://douban.8610000.xyz/movies.html 检索的时候看起来更清晰明了，而且方便把这个 json 文件导入到别的项目中做实时搜索，像豆瓣电影的搜索框一样的效果

![image](https://user-images.githubusercontent.com/19943786/129658255-7a6be76f-d698-4e51-89d0-e4d2f050d4a0.png)

**Comment by Taosky** [comment]
海报URL已经加进去了，不过文件体积大了不少😂，页面的话有空写一下试试效果。

**Comment by aizhimou** [comment]
> 海报URL已经加进去了，不过文件体积大了不少😂，页面的话有空写一下试试效果。

感谢朋友🎉 我看文件也就大了 2MB 左右，问题不大😄  非常感谢🍺🍺
