### ISSUE TITLE
按电影名称查询只能先获取所有，然后客户端进行筛选吗？

### ISSUE THREAD

**Issue by wander555** [Rocket-Factory/DoubanMovieJSON#2]
如题，没有相对应的api是吗？

**Comment by Taosky** [comment]
目前是的，因为只是用的Github Pages，没有查询的功能。

**Comment by Taosky** [comment]
新增了简单的电影标题检索 https://douban.8610000.xyz/suggest/<标题>.json（须将/ \ : * ? " < > |替换成_）
